### ISSUE TITLE
웰컴 메일 폼의 문구를 변경한다.

### ISSUE THREAD

**Issue by le2sky** [maeil-mail/maeil-mail-be#70]
- 주말에 보내지 않으니깐 금요일날 구독하면 다음주 월요일날 보낸다고 하거나,
- 아니면 "이제부터 면접 질문을 오전 7시에 보내 드릴게요! (주말에는 쉽니다)" 요런 느낌으로 가도 되고?
- 내일 중으로 이거 조치하고, 메일 폼 repo에 템플릿들 옮길 예정

**Comment by Parkhanyoung** [comment]
이제부터 면접 질문을 오전 7시에 보내 드릴게요.-> 이거 좋은 거 같아요!

구독 확인 메일뷰 제가 손봐서 올리겠습니다. 다 되면 아톰한테 한 번 더 말씀드릴게요!
